### ISSUE TITLE
Add URL to brpugesrd.xyz

### ISSUE THREAD

**Issue by nerun** [raleel/brpugesrd#1]
@raleel ,

Coul you add the URL to https://brpugesrd.xyz in the settings of this repository, as you did in [cfi-srd-pt](https://github.com/raleel/cfi-srd-pt)?

![repo](https://github.com/user-attachments/assets/4600dc9c-edb5-4e83-9b6b-406b12149751)

In cfi-srd-pt:
![cfi](https://github.com/user-attachments/assets/37e9eb37-9994-4ea2-8416-c2c0db3d96c8)

It would be nice to add the URL of your other repositories as well.

Just click gear icon. This icon just appears for the repository owner.
![about](https://github.com/user-attachments/assets/68b3f223-d54b-4b4d-ace1-49e67ce40065)

**Comment by raleel** [comment]
That I can. I’ll try to get to it this morning. Sent from my iPhoneOn Oct 18, 2024, at 5:02 AM, Daniel Dias Rodrigues ***@***.***> wrote:﻿
@raleel ,
Coul you add the URL to https://brpugesrd.xyz in the settings of this repository, as you did in cfi-srd-pt?
repo.jpg (view on web)
In cfi-srd-pt:
cfi.jpg (view on web)
It would be nice to add the URL of your other repositories as well.
Just click gear icon. This icon just appears for the repository owner.
about.jpg (view on web)

**Comment by raleel** [comment]
check it out now
